/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ade.food.order;

/**
 *
 * @author Ade Rizaldi
 */
public class CashierGUI extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    public CashierGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        btOrder = new javax.swing.JButton();
        btTrans = new javax.swing.JButton();
        btProfile = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        labelCash = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        llname = new javax.swing.JLabel();
        lladdress = new javax.swing.JLabel();
        lluser = new javax.swing.JLabel();
        orderPanel = new javax.swing.JPanel();
        orderLabel = new javax.swing.JLabel();
        drinkLabel1 = new javax.swing.JLabel();
        foodLabel1 = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        orderCombo = new javax.swing.JComboBox<>();
        foodPanel = new javax.swing.JPanel();
        noodleLabel = new javax.swing.JLabel();
        riceLabel = new javax.swing.JLabel();
        riceOrderLabel = new javax.swing.JLabel();
        noodleOrderLabel = new javax.swing.JLabel();
        riceAdd = new javax.swing.JButton();
        noodleAdd = new javax.swing.JButton();
        mealLabel = new javax.swing.JLabel();
        seaLabel = new javax.swing.JLabel();
        seaOrderLabel = new javax.swing.JLabel();
        meatOrderLabel = new javax.swing.JLabel();
        seaAdd = new javax.swing.JButton();
        meatAdd = new javax.swing.JButton();
        subFoodPanel = new javax.swing.JPanel();
        noodleScroll = new javax.swing.JScrollPane();
        noodleList = new javax.swing.JList<>();
        riceScroll = new javax.swing.JScrollPane();
        riceList = new javax.swing.JList<>();
        meatScroll = new javax.swing.JScrollPane();
        meatList = new javax.swing.JList<>();
        seaScroll = new javax.swing.JScrollPane();
        seaList = new javax.swing.JList<>();
        drinkPanel = new javax.swing.JPanel();
        hotLabel = new javax.swing.JLabel();
        coldLabel = new javax.swing.JLabel();
        coldAdd = new javax.swing.JButton();
        hotAdd = new javax.swing.JButton();
        coldOrderLabel = new javax.swing.JLabel();
        hotOrderLabel = new javax.swing.JLabel();
        subDrinkPanel = new javax.swing.JPanel();
        hotScroll = new javax.swing.JScrollPane();
        hotList = new javax.swing.JList<>();
        coldScroll = new javax.swing.JScrollPane();
        coldList = new javax.swing.JList<>();
        bestPanel = new javax.swing.JPanel();
        bestLabel = new javax.swing.JLabel();
        yourLabel = new javax.swing.JLabel();
        subBestPanel = new javax.swing.JPanel();
        bestScroll = new javax.swing.JScrollPane();
        bestList = new javax.swing.JList<>();
        yourScroll = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transPanel = new javax.swing.JPanel();
        labelTrans = new javax.swing.JLabel();
        scrollTrans = new javax.swing.JScrollPane();
        listTrans = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BasePanel.setBackground(new java.awt.Color(239, 225, 198));
        BasePanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        BasePanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        BasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(239, 225, 198));
        leftPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 110), 3, true));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btOrder.setText("Order");
        btOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrderActionPerformed(evt);
            }
        });
        leftPanel.add(btOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 35));

        btTrans.setText("Transactions");
        btTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransActionPerformed(evt);
            }
        });
        leftPanel.add(btTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 35));

        btProfile.setText("Profile");
        btProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftPanel.add(btProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 35));

        btLogout.setText("Logout");
        btLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftPanel.add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 100, 35));
        leftPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 100));

        BasePanel.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 600));

        rightPanel.setBackground(new java.awt.Color(239, 225, 198));
        rightPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 110), 3, true));
        rightPanel.setLayout(new java.awt.CardLayout());

        ProfilePanel.setBackground(new java.awt.Color(239, 225, 198));
        ProfilePanel.setPreferredSize(new java.awt.Dimension(850, 600));
        ProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCash.setBackground(new java.awt.Color(102, 102, 110));
        labelCash.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelCash.setForeground(new java.awt.Color(102, 102, 110));
        labelCash.setText("CASHIER");
        ProfilePanel.add(labelCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 23, -1, -1));

        labelName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 110));
        labelName.setText("Name :");
        ProfilePanel.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 132, -1, -1));

        labelAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(102, 102, 110));
        labelAddress.setText("Address :");
        ProfilePanel.add(labelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 197, -1, -1));

        labelUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(102, 102, 110));
        labelUser.setText("Username :");
        ProfilePanel.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 259, -1, -1));

        llname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        llname.setForeground(new java.awt.Color(102, 102, 110));
        llname.setText("Name");
        ProfilePanel.add(llname, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 132, 645, 30));

        lladdress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lladdress.setForeground(new java.awt.Color(102, 102, 110));
        lladdress.setText("Address");
        ProfilePanel.add(lladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 197, 645, 30));

        lluser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lluser.setForeground(new java.awt.Color(102, 102, 110));
        lluser.setText("User");
        ProfilePanel.add(lluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 259, 645, 30));

        rightPanel.add(ProfilePanel, "card2");

        orderPanel.setBackground(new java.awt.Color(239, 225, 198));
        orderPanel.setPreferredSize(new java.awt.Dimension(850, 600));
        orderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderLabel.setBackground(new java.awt.Color(102, 102, 110));
        orderLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        orderLabel.setForeground(new java.awt.Color(102, 102, 110));
        orderLabel.setText("ORDER");
        orderPanel.add(orderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        drinkLabel1.setBackground(new java.awt.Color(102, 102, 110));
        drinkLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        drinkLabel1.setForeground(new java.awt.Color(102, 102, 110));
        drinkLabel1.setText("DRINK");
        orderPanel.add(drinkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        foodLabel1.setBackground(new java.awt.Color(102, 102, 110));
        foodLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        foodLabel1.setForeground(new java.awt.Color(102, 102, 110));
        foodLabel1.setText("FOOD");
        orderPanel.add(foodLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        orderButton.setText("Order");
        orderPanel.add(orderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        orderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Take Away" }));
        orderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderComboActionPerformed(evt);
            }
        });
        orderPanel.add(orderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 110, -1));

        foodPanel.setBackground(new java.awt.Color(102, 102, 110));
        foodPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noodleLabel.setForeground(new java.awt.Color(250, 246, 234));
        noodleLabel.setText("Noodle");
        foodPanel.add(noodleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        riceLabel.setForeground(new java.awt.Color(250, 246, 234));
        riceLabel.setText("Rice");
        foodPanel.add(riceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        riceOrderLabel.setForeground(new java.awt.Color(250, 246, 234));
        riceOrderLabel.setText("jLabel3");
        foodPanel.add(riceOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        noodleOrderLabel.setForeground(new java.awt.Color(250, 246, 234));
        noodleOrderLabel.setText("jLabel3");
        foodPanel.add(noodleOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        riceAdd.setText("Add");
        riceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceAddActionPerformed(evt);
            }
        });
        foodPanel.add(riceAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 70, 30));

        noodleAdd.setText("Add");
        noodleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noodleAddActionPerformed(evt);
            }
        });
        foodPanel.add(noodleAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, 30));

        mealLabel.setForeground(new java.awt.Color(250, 246, 234));
        mealLabel.setText("Meat");
        foodPanel.add(mealLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        seaLabel.setForeground(new java.awt.Color(250, 246, 234));
        seaLabel.setText("Seafood");
        foodPanel.add(seaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        seaOrderLabel.setForeground(new java.awt.Color(250, 246, 234));
        seaOrderLabel.setText("jLabel3");
        foodPanel.add(seaOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        meatOrderLabel.setForeground(new java.awt.Color(250, 246, 234));
        meatOrderLabel.setText("jLabel3");
        foodPanel.add(meatOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        seaAdd.setText("Add");
        seaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaAddActionPerformed(evt);
            }
        });
        foodPanel.add(seaAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, 30));

        meatAdd.setText("Add");
        meatAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatAddActionPerformed(evt);
            }
        });
        foodPanel.add(meatAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 70, 30));

        subFoodPanel.setBackground(new java.awt.Color(102, 102, 110));
        subFoodPanel.setLayout(new javax.swing.BoxLayout(subFoodPanel, javax.swing.BoxLayout.X_AXIS));

        noodleScroll.setBackground(new java.awt.Color(102, 102, 110));

        noodleList.setBackground(new java.awt.Color(250, 246, 234));
        noodleList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        noodleList.setForeground(new java.awt.Color(102, 102, 110));
        noodleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        noodleScroll.setViewportView(noodleList);

        subFoodPanel.add(noodleScroll);

        riceScroll.setBackground(new java.awt.Color(102, 102, 110));

        riceList.setBackground(new java.awt.Color(250, 246, 234));
        riceList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        riceList.setForeground(new java.awt.Color(102, 102, 110));
        riceList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        riceScroll.setViewportView(riceList);

        subFoodPanel.add(riceScroll);

        meatScroll.setBackground(new java.awt.Color(102, 102, 110));

        meatList.setBackground(new java.awt.Color(250, 246, 234));
        meatList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        meatList.setForeground(new java.awt.Color(102, 102, 110));
        meatList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        meatScroll.setViewportView(meatList);

        subFoodPanel.add(meatScroll);

        seaScroll.setBackground(new java.awt.Color(102, 102, 110));

        seaList.setBackground(new java.awt.Color(250, 246, 234));
        seaList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        seaList.setForeground(new java.awt.Color(102, 102, 110));
        seaList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        seaScroll.setViewportView(seaList);

        subFoodPanel.add(seaScroll);

        foodPanel.add(subFoodPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 810, 160));

        orderPanel.add(foodPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 810, 230));

        drinkPanel.setBackground(new java.awt.Color(102, 102, 110));
        drinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotLabel.setForeground(new java.awt.Color(250, 246, 234));
        hotLabel.setText("Hot");
        drinkPanel.add(hotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        coldLabel.setForeground(new java.awt.Color(250, 246, 234));
        coldLabel.setText("Cold");
        drinkPanel.add(coldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        coldAdd.setText("Add");
        coldAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldAddActionPerformed(evt);
            }
        });
        drinkPanel.add(coldAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 70, 30));

        hotAdd.setText("Add");
        hotAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotAddActionPerformed(evt);
            }
        });
        drinkPanel.add(hotAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 70, 30));

        coldOrderLabel.setForeground(new java.awt.Color(250, 246, 234));
        coldOrderLabel.setText("jLabel3");
        drinkPanel.add(coldOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        hotOrderLabel.setForeground(new java.awt.Color(250, 246, 234));
        hotOrderLabel.setText("jLabel3");
        drinkPanel.add(hotOrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        subDrinkPanel.setBackground(new java.awt.Color(102, 102, 110));
        subDrinkPanel.setLayout(new javax.swing.BoxLayout(subDrinkPanel, javax.swing.BoxLayout.X_AXIS));

        hotScroll.setBackground(new java.awt.Color(102, 102, 110));

        hotList.setBackground(new java.awt.Color(250, 246, 234));
        hotList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hotList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        hotScroll.setViewportView(hotList);

        subDrinkPanel.add(hotScroll);

        coldScroll.setBackground(new java.awt.Color(102, 102, 110));

        coldList.setBackground(new java.awt.Color(250, 246, 234));
        coldList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        coldList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        coldScroll.setViewportView(coldList);

        subDrinkPanel.add(coldScroll);

        drinkPanel.add(subDrinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 140));

        orderPanel.add(drinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 410, 210));

        bestPanel.setBackground(new java.awt.Color(102, 102, 110));
        bestPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bestLabel.setForeground(new java.awt.Color(250, 246, 234));
        bestLabel.setText("Best Selling");
        bestPanel.add(bestLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        yourLabel.setForeground(new java.awt.Color(250, 246, 234));
        yourLabel.setText("Your Order");
        bestPanel.add(yourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        subBestPanel.setBackground(new java.awt.Color(102, 102, 110));
        subBestPanel.setLayout(new javax.swing.BoxLayout(subBestPanel, javax.swing.BoxLayout.X_AXIS));

        bestScroll.setBackground(new java.awt.Color(102, 102, 110));

        bestList.setBackground(new java.awt.Color(250, 246, 234));
        bestList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bestScroll.setViewportView(bestList);

        subBestPanel.add(bestScroll);

        yourScroll.setBackground(new java.awt.Color(102, 102, 110));

        orderList.setBackground(new java.awt.Color(250, 246, 234));
        orderList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        orderList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        yourScroll.setViewportView(orderList);

        subBestPanel.add(yourScroll);

        bestPanel.add(subBestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 380, 180));

        orderPanel.add(bestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 380, 210));

        jLabel1.setForeground(new java.awt.Color(102, 102, 110));
        jLabel1.setText("Total: ");
        orderPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 110));
        jLabel2.setText("jLabel2");
        orderPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 60, -1));

        rightPanel.add(orderPanel, "card2");

        transPanel.setBackground(new java.awt.Color(239, 225, 198));
        transPanel.setPreferredSize(new java.awt.Dimension(850, 600));
        transPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTrans.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTrans.setForeground(new java.awt.Color(102, 102, 110));
        labelTrans.setText("TRANSACTIONS");
        transPanel.add(labelTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 25, -1, -1));

        scrollTrans.setBorder(null);

        listTrans.setBackground(new java.awt.Color(239, 225, 198));
        listTrans.setForeground(new java.awt.Color(102, 102, 110));
        listTrans.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollTrans.setViewportView(listTrans);

        transPanel.add(scrollTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 69, 791, 456));

        rightPanel.add(transPanel, "card2");

        BasePanel.add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 600));

        getContentPane().add(BasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btOrderActionPerformed

    private void btTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTransActionPerformed

    private void coldAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldAddActionPerformed

    private void hotAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotAddActionPerformed

    private void riceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceAddActionPerformed

    private void noodleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noodleAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noodleAddActionPerformed

    private void seaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seaAddActionPerformed

    private void meatAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatAddActionPerformed

    private void orderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JLabel bestLabel;
    private javax.swing.JList<String> bestList;
    private javax.swing.JPanel bestPanel;
    private javax.swing.JScrollPane bestScroll;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btOrder;
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btTrans;
    private javax.swing.JButton coldAdd;
    private javax.swing.JLabel coldLabel;
    private javax.swing.JList<String> coldList;
    private javax.swing.JLabel coldOrderLabel;
    private javax.swing.JScrollPane coldScroll;
    private javax.swing.JLabel drinkLabel1;
    private javax.swing.JPanel drinkPanel;
    private javax.swing.JLabel foodLabel1;
    private javax.swing.JPanel foodPanel;
    private javax.swing.JButton hotAdd;
    private javax.swing.JLabel hotLabel;
    private javax.swing.JList<String> hotList;
    private javax.swing.JLabel hotOrderLabel;
    private javax.swing.JScrollPane hotScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelTrans;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JList<String> listTrans;
    private javax.swing.JLabel lladdress;
    private javax.swing.JLabel llname;
    private javax.swing.JLabel lluser;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel mealLabel;
    private javax.swing.JButton meatAdd;
    private javax.swing.JList<String> meatList;
    private javax.swing.JLabel meatOrderLabel;
    private javax.swing.JScrollPane meatScroll;
    private javax.swing.JButton noodleAdd;
    private javax.swing.JLabel noodleLabel;
    private javax.swing.JList<String> noodleList;
    private javax.swing.JLabel noodleOrderLabel;
    private javax.swing.JScrollPane noodleScroll;
    private javax.swing.JButton orderButton;
    private javax.swing.JComboBox<String> orderCombo;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JList<String> orderList;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JButton riceAdd;
    private javax.swing.JLabel riceLabel;
    private javax.swing.JList<String> riceList;
    private javax.swing.JLabel riceOrderLabel;
    private javax.swing.JScrollPane riceScroll;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JScrollPane scrollTrans;
    private javax.swing.JButton seaAdd;
    private javax.swing.JLabel seaLabel;
    private javax.swing.JList<String> seaList;
    private javax.swing.JLabel seaOrderLabel;
    private javax.swing.JScrollPane seaScroll;
    private javax.swing.JPanel subBestPanel;
    private javax.swing.JPanel subDrinkPanel;
    private javax.swing.JPanel subFoodPanel;
    private javax.swing.JPanel transPanel;
    private javax.swing.JLabel yourLabel;
    private javax.swing.JScrollPane yourScroll;
    // End of variables declaration//GEN-END:variables
}
