/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ade.food.order;

/**
 *
 * @author Ade Rizaldi
 */
public class ManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form Cashier
     */
    public ManagerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        btMenu = new javax.swing.JButton();
        btTrans2 = new javax.swing.JButton();
        btProfile2 = new javax.swing.JButton();
        btLogout2 = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        labelManag = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        llname = new javax.swing.JLabel();
        lladdress = new javax.swing.JLabel();
        lluser = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        drinkLabel1 = new javax.swing.JLabel();
        foodLabel1 = new javax.swing.JLabel();
        foodPanel = new javax.swing.JPanel();
        noodleLabel = new javax.swing.JLabel();
        riceLabel = new javax.swing.JLabel();
        riceAdd = new javax.swing.JButton();
        noodleAdd = new javax.swing.JButton();
        mealLabel = new javax.swing.JLabel();
        seaLabel = new javax.swing.JLabel();
        seaAdd = new javax.swing.JButton();
        meatAdd = new javax.swing.JButton();
        subFoodPanel = new javax.swing.JPanel();
        noodleScroll = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        riceScroll = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        meatScroll = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        seaScroll = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        drinkPanel = new javax.swing.JPanel();
        hotLabel = new javax.swing.JLabel();
        coldLabel = new javax.swing.JLabel();
        coldAdd = new javax.swing.JButton();
        hotAdd = new javax.swing.JButton();
        subDrinkPanel = new javax.swing.JPanel();
        hotScroll = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        coldScroll = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        transPanel = new javax.swing.JPanel();
        labelTrans = new javax.swing.JLabel();
        transLabel = new javax.swing.JLabel();
        transDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        scrollTrans = new javax.swing.JScrollPane();
        listTrans = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BasePanel.setBackground(new java.awt.Color(239, 225, 198));
        BasePanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        BasePanel.setMinimumSize(new java.awt.Dimension(1000, 600));
        BasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(239, 225, 198));
        leftPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 110), 3, true));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMenu.setText("Menu");
        btMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        leftPanel.add(btMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 35));

        btTrans2.setText("Transactions");
        btTrans2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTrans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrans2ActionPerformed(evt);
            }
        });
        leftPanel.add(btTrans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 35));

        btProfile2.setText("Profile");
        btProfile2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftPanel.add(btProfile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 35));

        btLogout2.setText("Logout");
        btLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leftPanel.add(btLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 100, 35));
        leftPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 100));

        BasePanel.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 600));

        rightPanel.setBackground(new java.awt.Color(239, 225, 198));
        rightPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 110), 3, true));
        rightPanel.setMaximumSize(new java.awt.Dimension(850, 600));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfilePanel.setBackground(new java.awt.Color(239, 225, 198));
        ProfilePanel.setMaximumSize(new java.awt.Dimension(850, 600));
        ProfilePanel.setMinimumSize(new java.awt.Dimension(850, 600));
        ProfilePanel.setPreferredSize(new java.awt.Dimension(850, 600));
        ProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelManag.setBackground(new java.awt.Color(102, 102, 110));
        labelManag.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        labelManag.setForeground(new java.awt.Color(102, 102, 110));
        labelManag.setText("MANAGER");
        ProfilePanel.add(labelManag, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 23, -1, -1));

        labelName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 102, 110));
        labelName.setText("Name :");
        ProfilePanel.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 132, -1, -1));

        labelAddress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelAddress.setForeground(new java.awt.Color(102, 102, 110));
        labelAddress.setText("Address :");
        ProfilePanel.add(labelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 197, -1, -1));

        labelUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(102, 102, 110));
        labelUser.setText("Username :");
        ProfilePanel.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 259, -1, -1));

        llname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        llname.setForeground(new java.awt.Color(102, 102, 110));
        ProfilePanel.add(llname, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 132, 645, 30));

        lladdress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lladdress.setForeground(new java.awt.Color(102, 102, 110));
        ProfilePanel.add(lladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 197, 645, 30));

        lluser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lluser.setForeground(new java.awt.Color(102, 102, 110));
        ProfilePanel.add(lluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 259, 645, 30));

        rightPanel.add(ProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        menuPanel.setBackground(new java.awt.Color(239, 225, 198));
        menuPanel.setMaximumSize(new java.awt.Dimension(850, 600));
        menuPanel.setMinimumSize(new java.awt.Dimension(850, 600));
        menuPanel.setPreferredSize(new java.awt.Dimension(850, 600));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drinkLabel1.setBackground(new java.awt.Color(102, 102, 110));
        drinkLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        drinkLabel1.setForeground(new java.awt.Color(102, 102, 110));
        drinkLabel1.setText("DRINK");
        menuPanel.add(drinkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        foodLabel1.setBackground(new java.awt.Color(102, 102, 110));
        foodLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        foodLabel1.setForeground(new java.awt.Color(102, 102, 110));
        foodLabel1.setText("FOOD");
        menuPanel.add(foodLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        foodPanel.setBackground(new java.awt.Color(102, 102, 110));
        foodPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noodleLabel.setForeground(new java.awt.Color(250, 246, 234));
        noodleLabel.setText("Noodle");
        foodPanel.add(noodleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        riceLabel.setForeground(new java.awt.Color(250, 246, 234));
        riceLabel.setText("Rice");
        foodPanel.add(riceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        riceAdd.setText("Add");
        riceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceAddActionPerformed(evt);
            }
        });
        foodPanel.add(riceAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 70, 30));

        noodleAdd.setText("Add");
        noodleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noodleAddActionPerformed(evt);
            }
        });
        foodPanel.add(noodleAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, 30));

        mealLabel.setForeground(new java.awt.Color(250, 246, 234));
        mealLabel.setText("Meat");
        foodPanel.add(mealLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        seaLabel.setForeground(new java.awt.Color(250, 246, 234));
        seaLabel.setText("Seafood");
        foodPanel.add(seaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        seaAdd.setText("Add");
        seaAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaAddActionPerformed(evt);
            }
        });
        foodPanel.add(seaAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 70, 30));

        meatAdd.setText("Add");
        meatAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatAddActionPerformed(evt);
            }
        });
        foodPanel.add(meatAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 70, 30));

        subFoodPanel.setBackground(new java.awt.Color(102, 102, 110));
        subFoodPanel.setLayout(new javax.swing.BoxLayout(subFoodPanel, javax.swing.BoxLayout.X_AXIS));

        noodleScroll.setBackground(new java.awt.Color(102, 102, 110));

        jList5.setBackground(new java.awt.Color(250, 246, 234));
        jList5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList5.setForeground(new java.awt.Color(102, 102, 110));
        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        noodleScroll.setViewportView(jList5);

        subFoodPanel.add(noodleScroll);

        riceScroll.setBackground(new java.awt.Color(102, 102, 110));

        jList6.setBackground(new java.awt.Color(250, 246, 234));
        jList6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList6.setForeground(new java.awt.Color(102, 102, 110));
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        riceScroll.setViewportView(jList6);

        subFoodPanel.add(riceScroll);

        meatScroll.setBackground(new java.awt.Color(102, 102, 110));

        jList7.setBackground(new java.awt.Color(250, 246, 234));
        jList7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList7.setForeground(new java.awt.Color(102, 102, 110));
        jList7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        meatScroll.setViewportView(jList7);

        subFoodPanel.add(meatScroll);

        seaScroll.setBackground(new java.awt.Color(102, 102, 110));

        jList8.setBackground(new java.awt.Color(250, 246, 234));
        jList8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList8.setForeground(new java.awt.Color(102, 102, 110));
        jList8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        seaScroll.setViewportView(jList8);

        subFoodPanel.add(seaScroll);

        foodPanel.add(subFoodPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 810, 160));

        menuPanel.add(foodPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 810, 230));

        drinkPanel.setBackground(new java.awt.Color(102, 102, 110));
        drinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotLabel.setForeground(new java.awt.Color(250, 246, 234));
        hotLabel.setText("Hot");
        drinkPanel.add(hotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        coldLabel.setForeground(new java.awt.Color(250, 246, 234));
        coldLabel.setText("Cold");
        drinkPanel.add(coldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        coldAdd.setText("Add");
        coldAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldAddActionPerformed(evt);
            }
        });
        drinkPanel.add(coldAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 70, 30));

        hotAdd.setText("Add");
        hotAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotAddActionPerformed(evt);
            }
        });
        drinkPanel.add(hotAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 70, 30));

        subDrinkPanel.setBackground(new java.awt.Color(102, 102, 110));
        subDrinkPanel.setLayout(new javax.swing.BoxLayout(subDrinkPanel, javax.swing.BoxLayout.X_AXIS));

        hotScroll.setBackground(new java.awt.Color(102, 102, 110));

        jList3.setBackground(new java.awt.Color(250, 246, 234));
        jList3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        hotScroll.setViewportView(jList3);

        subDrinkPanel.add(hotScroll);

        coldScroll.setBackground(new java.awt.Color(102, 102, 110));

        jList4.setBackground(new java.awt.Color(250, 246, 234));
        jList4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        coldScroll.setViewportView(jList4);

        subDrinkPanel.add(coldScroll);

        drinkPanel.add(subDrinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 140));

        menuPanel.add(drinkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 410, 210));

        rightPanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        transPanel.setBackground(new java.awt.Color(239, 225, 198));
        transPanel.setPreferredSize(new java.awt.Dimension(850, 600));
        transPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTrans.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTrans.setForeground(new java.awt.Color(102, 102, 110));
        labelTrans.setText("TRANSACTIONS");
        transPanel.add(labelTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 25, -1, -1));

        transLabel.setForeground(new java.awt.Color(102, 102, 110));
        transLabel.setText("jLabel1");
        transPanel.add(transLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        transDelete.setText("Delete");
        transPanel.add(transDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(239, 225, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTrans.setBorder(null);

        listTrans.setBackground(new java.awt.Color(239, 225, 198));
        listTrans.setForeground(new java.awt.Color(102, 102, 110));
        listTrans.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollTrans.setViewportView(listTrans);

        jPanel1.add(scrollTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 460));

        transPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 460));

        rightPanel.add(transPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        BasePanel.add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 600));

        getContentPane().add(BasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMenuActionPerformed

    private void btTrans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrans2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTrans2ActionPerformed

    private void riceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceAddActionPerformed

    private void noodleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noodleAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noodleAddActionPerformed

    private void seaAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seaAddActionPerformed

    private void meatAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatAddActionPerformed

    private void coldAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldAddActionPerformed

    private void hotAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JButton btLogout2;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btProfile2;
    private javax.swing.JButton btTrans2;
    private javax.swing.JButton coldAdd;
    private javax.swing.JLabel coldLabel;
    private javax.swing.JScrollPane coldScroll;
    private javax.swing.JLabel drinkLabel1;
    private javax.swing.JPanel drinkPanel;
    private javax.swing.JLabel foodLabel1;
    private javax.swing.JPanel foodPanel;
    private javax.swing.JButton hotAdd;
    private javax.swing.JLabel hotLabel;
    private javax.swing.JScrollPane hotScroll;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelManag;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelTrans;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JList<String> listTrans;
    private javax.swing.JLabel lladdress;
    private javax.swing.JLabel llname;
    private javax.swing.JLabel lluser;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel mealLabel;
    private javax.swing.JButton meatAdd;
    private javax.swing.JScrollPane meatScroll;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton noodleAdd;
    private javax.swing.JLabel noodleLabel;
    private javax.swing.JScrollPane noodleScroll;
    private javax.swing.JButton riceAdd;
    private javax.swing.JLabel riceLabel;
    private javax.swing.JScrollPane riceScroll;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JScrollPane scrollTrans;
    private javax.swing.JButton seaAdd;
    private javax.swing.JLabel seaLabel;
    private javax.swing.JScrollPane seaScroll;
    private javax.swing.JPanel subDrinkPanel;
    private javax.swing.JPanel subFoodPanel;
    private javax.swing.JButton transDelete;
    private javax.swing.JLabel transLabel;
    private javax.swing.JPanel transPanel;
    // End of variables declaration//GEN-END:variables
}
